import mongoose from "mongoose"

const bookSchema = new mongoose.Schema({
    bookName:{
        type:String,
        required:true,
    },
    bookAuthor:{
        type:String,
        required:true,
    },
    bookBrief:{
        type:String
    },
    autoGenerated:{
        type:Boolean,
        default:false
    },
    userGenerated:{
        type:Boolean,
        default:false
    }
})

const Book = mongoose.model("Book", bookSchema)
export default Book